language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get install swig
  - sudo apt-get install python-numpy python-scipy
  - ./install-slatkin-tools.sh
  - ./install-nauty.sh
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests
