#!/usr/bin/env python
# Copyright (c) 2013.  Mark E. Madsen <mark@madsenlab.org>
#
# This work is licensed under the terms of the Apache Software License, Version 2.0.  See the file LICENSE for details.


"""
Generates a parameter document (to STDOUT) for a given configuration file.  Allows a choice of
LaTeX and Markdown (Pandoc) formats.

"""


import logging as log
import argparse
import madsenlab.axelrod.utils as utils





def setup():
    global args

    parser = argparse.ArgumentParser()
    parser.add_argument("--configuration", help="Configuration file for experiment", required=True)
    parser.add_argument("--experiment", help="provide name for experiment", required=True)
    parser.add_argument("--format", choices=['latex', 'pandoc'], help="Format for output ", required=True)
    parser.add_argument("--debug", help="turn on debugging output")
    parser.add_argument("--caption", help="Optional table caption (one will be autogenerated otherwise)")


    args = parser.parse_args()

    if args.debug:
        log.basicConfig(level=log.DEBUG, format='%(asctime)s %(levelname)s: %(message)s')
    else:
        log.basicConfig(level=log.INFO, format='%(asctime)s %(levelname)s: %(message)s')



####### main loop #######

if __name__ == "__main__":
    setup()
    simconfig = utils.AxelrodConfiguration(args.configuration)

    if args.caption:
        caption = args.caption
    else:
        caption = None


    if args.format == 'pandoc':
        print simconfig.to_pandoc_table(args.experiment, caption=caption)
    elif args.format == 'latex':
        print simconfig.to_latex_table(args.experiment, caption=caption)
    else:
        print "Unrecognized format: %s" % args.format
        exit(1)


    exit(0)

